# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bot/netbeans/NetBeansProjects/ba/agaifaceanalysis.git.cpt

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bot/netbeans/NetBeansProjects/ba/agaifaceanalysis.git.cpt

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bot/netbeans/NetBeansProjects/ba/agaifaceanalysis.git.cpt/CMakeFiles /home/bot/netbeans/NetBeansProjects/ba/agaifaceanalysis.git.cpt/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bot/netbeans/NetBeansProjects/ba/agaifaceanalysis.git.cpt/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CPT_Evaluation_Local

# Build rule for target.
CPT_Evaluation_Local: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CPT_Evaluation_Local
.PHONY : CPT_Evaluation_Local

# fast build rule for target.
CPT_Evaluation_Local/fast:
	$(MAKE) -f CMakeFiles/CPT_Evaluation_Local.dir/build.make CMakeFiles/CPT_Evaluation_Local.dir/build
.PHONY : CPT_Evaluation_Local/fast

src/main_evaluation_local.o: src/main_evaluation_local.cpp.o
.PHONY : src/main_evaluation_local.o

# target to build an object file
src/main_evaluation_local.cpp.o:
	$(MAKE) -f CMakeFiles/CPT_Evaluation_Local.dir/build.make CMakeFiles/CPT_Evaluation_Local.dir/src/main_evaluation_local.cpp.o
.PHONY : src/main_evaluation_local.cpp.o

src/main_evaluation_local.i: src/main_evaluation_local.cpp.i
.PHONY : src/main_evaluation_local.i

# target to preprocess a source file
src/main_evaluation_local.cpp.i:
	$(MAKE) -f CMakeFiles/CPT_Evaluation_Local.dir/build.make CMakeFiles/CPT_Evaluation_Local.dir/src/main_evaluation_local.cpp.i
.PHONY : src/main_evaluation_local.cpp.i

src/main_evaluation_local.s: src/main_evaluation_local.cpp.s
.PHONY : src/main_evaluation_local.s

# target to generate assembly for a file
src/main_evaluation_local.cpp.s:
	$(MAKE) -f CMakeFiles/CPT_Evaluation_Local.dir/build.make CMakeFiles/CPT_Evaluation_Local.dir/src/main_evaluation_local.cpp.s
.PHONY : src/main_evaluation_local.cpp.s

src/model/dataHandlers/DatasetHandler.o: src/model/dataHandlers/DatasetHandler.cpp.o
.PHONY : src/model/dataHandlers/DatasetHandler.o

# target to build an object file
src/model/dataHandlers/DatasetHandler.cpp.o:
	$(MAKE) -f CMakeFiles/CPT_Evaluation_Local.dir/build.make CMakeFiles/CPT_Evaluation_Local.dir/src/model/dataHandlers/DatasetHandler.cpp.o
.PHONY : src/model/dataHandlers/DatasetHandler.cpp.o

src/model/dataHandlers/DatasetHandler.i: src/model/dataHandlers/DatasetHandler.cpp.i
.PHONY : src/model/dataHandlers/DatasetHandler.i

# target to preprocess a source file
src/model/dataHandlers/DatasetHandler.cpp.i:
	$(MAKE) -f CMakeFiles/CPT_Evaluation_Local.dir/build.make CMakeFiles/CPT_Evaluation_Local.dir/src/model/dataHandlers/DatasetHandler.cpp.i
.PHONY : src/model/dataHandlers/DatasetHandler.cpp.i

src/model/dataHandlers/DatasetHandler.s: src/model/dataHandlers/DatasetHandler.cpp.s
.PHONY : src/model/dataHandlers/DatasetHandler.s

# target to generate assembly for a file
src/model/dataHandlers/DatasetHandler.cpp.s:
	$(MAKE) -f CMakeFiles/CPT_Evaluation_Local.dir/build.make CMakeFiles/CPT_Evaluation_Local.dir/src/model/dataHandlers/DatasetHandler.cpp.s
.PHONY : src/model/dataHandlers/DatasetHandler.cpp.s

src/model/detectors/ViolaLienhartDetector.o: src/model/detectors/ViolaLienhartDetector.cpp.o
.PHONY : src/model/detectors/ViolaLienhartDetector.o

# target to build an object file
src/model/detectors/ViolaLienhartDetector.cpp.o:
	$(MAKE) -f CMakeFiles/CPT_Evaluation_Local.dir/build.make CMakeFiles/CPT_Evaluation_Local.dir/src/model/detectors/ViolaLienhartDetector.cpp.o
.PHONY : src/model/detectors/ViolaLienhartDetector.cpp.o

src/model/detectors/ViolaLienhartDetector.i: src/model/detectors/ViolaLienhartDetector.cpp.i
.PHONY : src/model/detectors/ViolaLienhartDetector.i

# target to preprocess a source file
src/model/detectors/ViolaLienhartDetector.cpp.i:
	$(MAKE) -f CMakeFiles/CPT_Evaluation_Local.dir/build.make CMakeFiles/CPT_Evaluation_Local.dir/src/model/detectors/ViolaLienhartDetector.cpp.i
.PHONY : src/model/detectors/ViolaLienhartDetector.cpp.i

src/model/detectors/ViolaLienhartDetector.s: src/model/detectors/ViolaLienhartDetector.cpp.s
.PHONY : src/model/detectors/ViolaLienhartDetector.s

# target to generate assembly for a file
src/model/detectors/ViolaLienhartDetector.cpp.s:
	$(MAKE) -f CMakeFiles/CPT_Evaluation_Local.dir/build.make CMakeFiles/CPT_Evaluation_Local.dir/src/model/detectors/ViolaLienhartDetector.cpp.s
.PHONY : src/model/detectors/ViolaLienhartDetector.cpp.s

src/model/evaluation/Evaluator.o: src/model/evaluation/Evaluator.cpp.o
.PHONY : src/model/evaluation/Evaluator.o

# target to build an object file
src/model/evaluation/Evaluator.cpp.o:
	$(MAKE) -f CMakeFiles/CPT_Evaluation_Local.dir/build.make CMakeFiles/CPT_Evaluation_Local.dir/src/model/evaluation/Evaluator.cpp.o
.PHONY : src/model/evaluation/Evaluator.cpp.o

src/model/evaluation/Evaluator.i: src/model/evaluation/Evaluator.cpp.i
.PHONY : src/model/evaluation/Evaluator.i

# target to preprocess a source file
src/model/evaluation/Evaluator.cpp.i:
	$(MAKE) -f CMakeFiles/CPT_Evaluation_Local.dir/build.make CMakeFiles/CPT_Evaluation_Local.dir/src/model/evaluation/Evaluator.cpp.i
.PHONY : src/model/evaluation/Evaluator.cpp.i

src/model/evaluation/Evaluator.s: src/model/evaluation/Evaluator.cpp.s
.PHONY : src/model/evaluation/Evaluator.s

# target to generate assembly for a file
src/model/evaluation/Evaluator.cpp.s:
	$(MAKE) -f CMakeFiles/CPT_Evaluation_Local.dir/build.make CMakeFiles/CPT_Evaluation_Local.dir/src/model/evaluation/Evaluator.cpp.s
.PHONY : src/model/evaluation/Evaluator.cpp.s

src/model/evaluation/LocalEvaluator.o: src/model/evaluation/LocalEvaluator.cpp.o
.PHONY : src/model/evaluation/LocalEvaluator.o

# target to build an object file
src/model/evaluation/LocalEvaluator.cpp.o:
	$(MAKE) -f CMakeFiles/CPT_Evaluation_Local.dir/build.make CMakeFiles/CPT_Evaluation_Local.dir/src/model/evaluation/LocalEvaluator.cpp.o
.PHONY : src/model/evaluation/LocalEvaluator.cpp.o

src/model/evaluation/LocalEvaluator.i: src/model/evaluation/LocalEvaluator.cpp.i
.PHONY : src/model/evaluation/LocalEvaluator.i

# target to preprocess a source file
src/model/evaluation/LocalEvaluator.cpp.i:
	$(MAKE) -f CMakeFiles/CPT_Evaluation_Local.dir/build.make CMakeFiles/CPT_Evaluation_Local.dir/src/model/evaluation/LocalEvaluator.cpp.i
.PHONY : src/model/evaluation/LocalEvaluator.cpp.i

src/model/evaluation/LocalEvaluator.s: src/model/evaluation/LocalEvaluator.cpp.s
.PHONY : src/model/evaluation/LocalEvaluator.s

# target to generate assembly for a file
src/model/evaluation/LocalEvaluator.cpp.s:
	$(MAKE) -f CMakeFiles/CPT_Evaluation_Local.dir/build.make CMakeFiles/CPT_Evaluation_Local.dir/src/model/evaluation/LocalEvaluator.cpp.s
.PHONY : src/model/evaluation/LocalEvaluator.cpp.s

src/model/local/Gauss.o: src/model/local/Gauss.cpp.o
.PHONY : src/model/local/Gauss.o

# target to build an object file
src/model/local/Gauss.cpp.o:
	$(MAKE) -f CMakeFiles/CPT_Evaluation_Local.dir/build.make CMakeFiles/CPT_Evaluation_Local.dir/src/model/local/Gauss.cpp.o
.PHONY : src/model/local/Gauss.cpp.o

src/model/local/Gauss.i: src/model/local/Gauss.cpp.i
.PHONY : src/model/local/Gauss.i

# target to preprocess a source file
src/model/local/Gauss.cpp.i:
	$(MAKE) -f CMakeFiles/CPT_Evaluation_Local.dir/build.make CMakeFiles/CPT_Evaluation_Local.dir/src/model/local/Gauss.cpp.i
.PHONY : src/model/local/Gauss.cpp.i

src/model/local/Gauss.s: src/model/local/Gauss.cpp.s
.PHONY : src/model/local/Gauss.s

# target to generate assembly for a file
src/model/local/Gauss.cpp.s:
	$(MAKE) -f CMakeFiles/CPT_Evaluation_Local.dir/build.make CMakeFiles/CPT_Evaluation_Local.dir/src/model/local/Gauss.cpp.s
.PHONY : src/model/local/Gauss.cpp.s

src/model/local/LocalPolynoms.o: src/model/local/LocalPolynoms.cpp.o
.PHONY : src/model/local/LocalPolynoms.o

# target to build an object file
src/model/local/LocalPolynoms.cpp.o:
	$(MAKE) -f CMakeFiles/CPT_Evaluation_Local.dir/build.make CMakeFiles/CPT_Evaluation_Local.dir/src/model/local/LocalPolynoms.cpp.o
.PHONY : src/model/local/LocalPolynoms.cpp.o

src/model/local/LocalPolynoms.i: src/model/local/LocalPolynoms.cpp.i
.PHONY : src/model/local/LocalPolynoms.i

# target to preprocess a source file
src/model/local/LocalPolynoms.cpp.i:
	$(MAKE) -f CMakeFiles/CPT_Evaluation_Local.dir/build.make CMakeFiles/CPT_Evaluation_Local.dir/src/model/local/LocalPolynoms.cpp.i
.PHONY : src/model/local/LocalPolynoms.cpp.i

src/model/local/LocalPolynoms.s: src/model/local/LocalPolynoms.cpp.s
.PHONY : src/model/local/LocalPolynoms.s

# target to generate assembly for a file
src/model/local/LocalPolynoms.cpp.s:
	$(MAKE) -f CMakeFiles/CPT_Evaluation_Local.dir/build.make CMakeFiles/CPT_Evaluation_Local.dir/src/model/local/LocalPolynoms.cpp.s
.PHONY : src/model/local/LocalPolynoms.cpp.s

src/model/local/PatchFeature.o: src/model/local/PatchFeature.cpp.o
.PHONY : src/model/local/PatchFeature.o

# target to build an object file
src/model/local/PatchFeature.cpp.o:
	$(MAKE) -f CMakeFiles/CPT_Evaluation_Local.dir/build.make CMakeFiles/CPT_Evaluation_Local.dir/src/model/local/PatchFeature.cpp.o
.PHONY : src/model/local/PatchFeature.cpp.o

src/model/local/PatchFeature.i: src/model/local/PatchFeature.cpp.i
.PHONY : src/model/local/PatchFeature.i

# target to preprocess a source file
src/model/local/PatchFeature.cpp.i:
	$(MAKE) -f CMakeFiles/CPT_Evaluation_Local.dir/build.make CMakeFiles/CPT_Evaluation_Local.dir/src/model/local/PatchFeature.cpp.i
.PHONY : src/model/local/PatchFeature.cpp.i

src/model/local/PatchFeature.s: src/model/local/PatchFeature.cpp.s
.PHONY : src/model/local/PatchFeature.s

# target to generate assembly for a file
src/model/local/PatchFeature.cpp.s:
	$(MAKE) -f CMakeFiles/CPT_Evaluation_Local.dir/build.make CMakeFiles/CPT_Evaluation_Local.dir/src/model/local/PatchFeature.cpp.s
.PHONY : src/model/local/PatchFeature.cpp.s

src/model/local/PatchFeatureUtils.o: src/model/local/PatchFeatureUtils.cpp.o
.PHONY : src/model/local/PatchFeatureUtils.o

# target to build an object file
src/model/local/PatchFeatureUtils.cpp.o:
	$(MAKE) -f CMakeFiles/CPT_Evaluation_Local.dir/build.make CMakeFiles/CPT_Evaluation_Local.dir/src/model/local/PatchFeatureUtils.cpp.o
.PHONY : src/model/local/PatchFeatureUtils.cpp.o

src/model/local/PatchFeatureUtils.i: src/model/local/PatchFeatureUtils.cpp.i
.PHONY : src/model/local/PatchFeatureUtils.i

# target to preprocess a source file
src/model/local/PatchFeatureUtils.cpp.i:
	$(MAKE) -f CMakeFiles/CPT_Evaluation_Local.dir/build.make CMakeFiles/CPT_Evaluation_Local.dir/src/model/local/PatchFeatureUtils.cpp.i
.PHONY : src/model/local/PatchFeatureUtils.cpp.i

src/model/local/PatchFeatureUtils.s: src/model/local/PatchFeatureUtils.cpp.s
.PHONY : src/model/local/PatchFeatureUtils.s

# target to generate assembly for a file
src/model/local/PatchFeatureUtils.cpp.s:
	$(MAKE) -f CMakeFiles/CPT_Evaluation_Local.dir/build.make CMakeFiles/CPT_Evaluation_Local.dir/src/model/local/PatchFeatureUtils.cpp.s
.PHONY : src/model/local/PatchFeatureUtils.cpp.s

src/model/local/Polynom.o: src/model/local/Polynom.cpp.o
.PHONY : src/model/local/Polynom.o

# target to build an object file
src/model/local/Polynom.cpp.o:
	$(MAKE) -f CMakeFiles/CPT_Evaluation_Local.dir/build.make CMakeFiles/CPT_Evaluation_Local.dir/src/model/local/Polynom.cpp.o
.PHONY : src/model/local/Polynom.cpp.o

src/model/local/Polynom.i: src/model/local/Polynom.cpp.i
.PHONY : src/model/local/Polynom.i

# target to preprocess a source file
src/model/local/Polynom.cpp.i:
	$(MAKE) -f CMakeFiles/CPT_Evaluation_Local.dir/build.make CMakeFiles/CPT_Evaluation_Local.dir/src/model/local/Polynom.cpp.i
.PHONY : src/model/local/Polynom.cpp.i

src/model/local/Polynom.s: src/model/local/Polynom.cpp.s
.PHONY : src/model/local/Polynom.s

# target to generate assembly for a file
src/model/local/Polynom.cpp.s:
	$(MAKE) -f CMakeFiles/CPT_Evaluation_Local.dir/build.make CMakeFiles/CPT_Evaluation_Local.dir/src/model/local/Polynom.cpp.s
.PHONY : src/model/local/Polynom.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... CPT_Evaluation_Local"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... install/local"
	@echo "... src/main_evaluation_local.o"
	@echo "... src/main_evaluation_local.i"
	@echo "... src/main_evaluation_local.s"
	@echo "... src/model/dataHandlers/DatasetHandler.o"
	@echo "... src/model/dataHandlers/DatasetHandler.i"
	@echo "... src/model/dataHandlers/DatasetHandler.s"
	@echo "... src/model/detectors/ViolaLienhartDetector.o"
	@echo "... src/model/detectors/ViolaLienhartDetector.i"
	@echo "... src/model/detectors/ViolaLienhartDetector.s"
	@echo "... src/model/evaluation/Evaluator.o"
	@echo "... src/model/evaluation/Evaluator.i"
	@echo "... src/model/evaluation/Evaluator.s"
	@echo "... src/model/evaluation/LocalEvaluator.o"
	@echo "... src/model/evaluation/LocalEvaluator.i"
	@echo "... src/model/evaluation/LocalEvaluator.s"
	@echo "... src/model/local/Gauss.o"
	@echo "... src/model/local/Gauss.i"
	@echo "... src/model/local/Gauss.s"
	@echo "... src/model/local/LocalPolynoms.o"
	@echo "... src/model/local/LocalPolynoms.i"
	@echo "... src/model/local/LocalPolynoms.s"
	@echo "... src/model/local/PatchFeature.o"
	@echo "... src/model/local/PatchFeature.i"
	@echo "... src/model/local/PatchFeature.s"
	@echo "... src/model/local/PatchFeatureUtils.o"
	@echo "... src/model/local/PatchFeatureUtils.i"
	@echo "... src/model/local/PatchFeatureUtils.s"
	@echo "... src/model/local/Polynom.o"
	@echo "... src/model/local/Polynom.i"
	@echo "... src/model/local/Polynom.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

